#!/bin/bash
# dotfiles deployment for crunchbang
# after git cloning the repo to ~/dotfiles
# uncomment src repos in sources.list then do

sudo apt-get update
sudo apt-get install mercurial

#vim
cd ~
sh dotfiles/install_vim.sh
ln -s ~/dotfiles/vimrc .vimrc
ln -s ~/dotfiles/vim .vim

#conky
cd ~
mv .conkyrc .conkyrc.old
ln -s ~/dotfiles/conkyrc .conkyrc
killall -SIGUSR1 conky

#autostart
cd ~/.config/openbox/
mv autostart autostart.old
ln -s ~/dotfiles/autostart autostart

# rc.xml
cd ~/.config/openbox/
mv rc.xml rc.xml.old
ln -s ~/dotfiles/rc.xml rc.xml
openbox --reconfigure
